!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! Euler44 ~ Pentagon numbers
! 
! Problem Statement:
! 
! Pentagonal numbers are generated by the formula, P(n)=n(3n−1)/2.
! The first ten pentagonal numbers are:
! 
!		1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
! 
! It can be seen that P(4) + P(7) = 22 + 70 = 92 = P(8). However,
! their difference, 70 − 22 = 48, is not pentagonal.
! 
! Find the pair of pentagonal numbers, Pj and Pk, for which their
! sum and difference are pentagonal and D = |Pk − Pj| is minimised;
! what is the value of D?
!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! Algorithm Explanation:
! 
! List of pentagonal numbers are created at start for reference
! during the main loop. For loops pick two values to test for
! pentagonality and then checks the sum and diff. If it passes we
! set solution to the difference.
!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

program Euler44
	
	implicit none
	integer :: time_start, time_finish, clock_finish, solution = 0
	integer :: i,j,sum_,diff
	integer, dimension(2500) :: pentas = 0
	
	call SYSTEM_CLOCK(time_start)

	do i = 0,2499
		pentas(i+1) = i * (3 * i - 1) / 2
	end do
	
	do i = 1,2499
		do j = (i+1),2499
			sum_ = pentas(i+1) + pentas(j+1)
			diff = abs(pentas(i+1)-pentas(j+1))
			!if ( ANY( lastNeighArray=="n" ) ) then
			if (ANY(pentas==diff) .and. ANY(pentas==sum_)) then
				solution = diff
				EXIT
			end if
		end do
	end do
	
	call SYSTEM_CLOCK(time_finish)
	clock_finish = time_finish - time_start
	write (*,"(A10,I10,//,A21,I5,A14)") "Solution: ",solution,"Program completed in ",clock_finish," milliseconds."

end program Euler44
