!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! Euler45 ~ Triangular, pentagonal, and hexagonal
! 
! Problem Statement:
! 
! Triangle, pentagonal, and hexagonal numbers are generated by the
! following formulae:
! 
!      Triangle        T(n) = n(n+1)/2       1, 3,  6, 10, 15, ...
!      Pentagonal      P(n) = n(3n−1)/2      1, 5, 12, 22, 35, ...
!      Hexagonal       H(n) = n(2n−1)        1, 6, 15, 28, 45, ...
!
! It can be verified that T(285) = P(165) = H(143) = 40755.
! 
! Find the next triangle number that is also pentagonal and
! hexagonal.
!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! Algorithm Explanation:
! 
! All hexagonal numbers are triangular numbers, so checking for
! triangular numbers can be ignored. Hexagonal numbers are generated
! according to the corresponding equation and then checked to see
! if the value is also a pentagonal number.
!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

program Euler45
	
	implicit none
	integer :: time_start, time_finish, clock_finish, solution = 0
	integer :: Hn, i
	call SYSTEM_CLOCK(time_start)
	
	do i = 144,30000
		Hn = i * (2 * i - 1)
		if (isPentagonal(Hn)) then
			solution = Hn
			EXIT
		end if
	end do

	call SYSTEM_CLOCK(time_finish)
	clock_finish = time_finish - time_start
	write (*,"(A10,I10,//,A21,I5,A14)") "Solution: ",solution,"Program completed in ",clock_finish," milliseconds."

contains

	logical function isPentagonal(num)
		integer :: num, i
		integer, parameter :: LargeInt_K = selected_int_kind (18)
		integer (kind=LargeInt_K) :: Pn = 0, n = 1
		
		do while(Pn < num)
			Pn = n * (3*n - 1) / 2
			if (Pn == num) then
				isPentagonal = .true.
				return
			end if
			n = n + 1
		end do
		isPentagonal = .false.
		return
    end
	
end program Euler45
