!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! Euler29 ~ Distinct powers
! 
! Problem Statement:
! 
! Consider all integer combinations of a^b for 2 <= a <= 5 and
! 2 <= b <= 5:
! 
!      2^2 = 4,  2^3 = 8,    2^4 = 16,  2^5 = 32
!      3^2 = 9,  3^3 = 27,   3^4 = 81,  3^5 = 243
!      4^2 = 16  4^3 = 64,   4^4 = 256, 4^5 = 1024
!      5^2 = 25, 5^3 = 125,  5^4 = 625, 5^5 = 3125
! 
! If they are then placed in numerical order, with any repeats
! removed, we get the following sequence of 15 distinct terms:
! 
! 4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125
! 
! How many distinct terms are in the sequence generated by
! a^b for 2 <= a <= 100 and 2 <= b <= 100?
!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! Algorithm Explanation:
! 
! FM library is used to calculate large values of the exponents
! before converting to strings for comparison and storage.
!
! Compilation --> Compiled using MinGw & Windows PowerShell
!		  	          gfortran Euler29.f90 -c -O3
!                 gfortran fmsave.o FM.o FMZM90.o Euler29.o -o Euler29
!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

program Euler29
	use FMZM
	
	implicit none
	integer :: time_start, time_finish, clock_finish, solution = 0
	
	integer :: a, b
	
	TYPE(IM), SAVE :: ROP, BIG_a, BIG_b
	
	character(210) :: STR
	character(210), dimension(9183) :: numbers
	
	call SYSTEM_CLOCK(time_start)

	do a = 2,100
		do b = 2,100
			BIG_a = TO_IM(a)
			BIG_b = TO_IM(b)
			ROP = BIG_a ** BIG_b
			CALL IM_FORM('I210',ROP,STR)
			if (ANY(numbers==STR)) then
				!number was found already
			else
				solution = solution + 1
				numbers(solution) = STR
			end if
		end do
	end do

	call SYSTEM_CLOCK(time_finish)
	clock_finish = time_finish - time_start
	write (*,"(A10,I10,//,A21,I5,A14)") "Solution: ",solution,"Program completed in ",clock_finish," milliseconds."

end program Euler29
